behaviors:
  NoCheckpointDriving:
    trainer_type: sac
    hyperparameters:
      batch_size: 256
      buffer_size: 1000000
      learning_rate: 3.0e-4
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 5000000
    threaded: false
    time_horizon: 64
    summary_freq: 100000